spring.application.name=app-apis
# Database Configuration
spring.datasource.url=postgresql://neondb_owner:****************@ep-old-tree-aq9fsb6z-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=postgres
spring.datasource.password=password

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=wG56XdOIpWF8hQSk1e5Fo5rOi9CAzi6FjGHf0fWciS7
jwt.expiration=86400000

# Resend Configuration
resend.api-key=YOUR_RESEND_API_KEY
resend.from-email=noreply@yourdomain.com